### ISSUE TITLE
Todo after July 2019

### ISSUE THREAD

**Issue by SeanWong24** [vgalab/temp#1]
Todo 1
---
- [ ] giving interface control for run.sh
- [x] limit the # of clone check box to 100
- [ ] tab for the cloneworld editor
- [x] add a vertical axis to the end of the parallel coordinate that connects all the clones in sorted order with uniform gap in between
- [x] map the height of the lines /change count to a logarithmic mapping
- [ ] updating the checkbox based on user selection  
- [x] only show clones existing last revision in parallel coordinate

Todo 2
---
- [ ] Think about how to show that a clone has been changed recently - option is to run nicad and generate another revision axis
- [ ] giving the user option to push to the git repository - provide integrated terminal - we are not giving support for debug at this point through the editor  

Todo 3
---
- [ ] File Treemap
- [ ] Replace CloneLandscape - using clone heatmap with clustering
- [ ] Merge Vis3 and Vis4 and bring GraphLayout for different types of clones

Done 
---
- [x] generating Nicad report (temp) and geneology report ($output_path) by running run.sh directly from git master checkout
- [x] open repository through the cloneword interface for opening files
- [x] open reports path to generate parallel coordinate
- [x] parallel coordinate shows the highly changing clones
- [x] clones are sorted based on the change count (changes in the # of revisions)
- [x] select checkbox and open a file in the code editor (supports for clone world and system editor), the clone is highlighted in the left panel of the editor
- [x] edit and save functionality of the clone world editor
